### ISSUE TITLE
Account and Alert Data

### ISSUE THREAD

**Issue by macjeff** [bpaauwe/udi-aeris-poly#1]
I would love to test this but $80 a month they charge is pretty steep for a home user.  Any options for cheaper service?

Also one thing Aeris offers that I dont see in other node servers (or in your docs) is ALERT info.  Would be nice to get alerts in the ISY so for example if a tornado warning blink lights in house. (just made that up but you get the idea).

**Comment by bpaauwe** [comment]
Alerts tend to be difficult to integrate into the ISY because they are usually text based and are quite varied. I haven't looked at Aeris alerts specifically though.

**Comment by macjeff** [comment]
Talked to Aeris and they said their alerts cost about 1000 a month,  but they are willing to do a cheaper sub for UDI that allows all their API users to get alerts.  PM me if you want to talk.  

Jeff

**Comment by bpaauwe** [comment]
I don't work for UDI and can't negotiate on their behalf.  Writing the node servers is something I've been doing in my free time.

**Comment by macjeff** [comment]
they wont accept Weatherflow for their PWS plan and seems like UDI does not want to work with them so I am closing this issue
