### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by Smileyone** [bpaauwe/udi-aeris-poly#31]
Hello, I installed the nodes server on Polyglot-V2 but it doesn't install correctly, the configuration section is partially missing and the nodes don't appear.
This is the log output, any assistance would be greatly appreciated.
[AERISWeather_2-9-2021_95030_AM.txt](https://github.com/bpaauwe/udi-aeris-poly/files/5952258/AERISWeather_2-9-2021_95030_AM.txt)

Thank you.

**Comment by bpaauwe** [comment]
Based on what's in the log, it's not the Aeris node server that's failing.  It looks like the interface module can't communicate with Polyglot possibly because something is wrong with the SSL setup on the box.

**Comment by Smileyone** [comment]
Okay, thank you very much.
