### ISSUE TITLE
Metric Updates needed

### ISSUE THREAD

**Issue by CompKingCanada** [bpaauwe/udi-aeris-poly#8]
Units for wind-speed are calc'd at km/hr but show as m/s
Update lower range for -10c being lower limit to -50c

Patches Pending
#3 #4 #5 #6 #7 

In the future, I will try to combine these into a single pull request

**Comment by bpaauwe** [comment]
No need.  I actually like having separate patches for separate changes.   It is a lot easier to debug and revert something if it's an isolated change.
