### ISSUE TITLE
Eto Calculation seems quite low

### ISSUE THREAD

**Issue by CompKingCanada** [bpaauwe/udi-aeris-poly#9]
The end goal of the updates I have been giving is to get my Irrigation System back to where it was before the ISY Climate Module was removed.

In the middle of Summer in Canada on windy days, the ETo numbers being calculated of .67mm/day is very low.  I would expect greater than 3mm/day

I am trying to compare your base test scenario in the et3.py to another model to validate the accuracy of the calculation.  Not a simple task from what I can see.  Right now I am using someone else's ETo calculator at: http://www.fao.org/land-water/databases-and-software/eto-calculator/en/ to validate..

Do you have an external model you used when developing your source so I could try to get closer to your numbers?

**Comment by bpaauwe** [comment]
The source of the model is referenced in the et3.py file:
http://edis.ifas.ufl.edu/pdffiles/ae/ae45900.pdf

I also compared the results with the ETo calculations from RainMachine and Weewx.  And I checked the results against the NOAA published ETo.

That said, it seems like it doesn't take much of a change is certain input values to cause fairly large differences in the ETo.  There also are some simplifications done depending on what inputs are available.

**Comment by CompKingCanada** [comment]
Based upon what I derived with my current forecast from Aeris, my calc'd ET0 should be 7.26 mm/day.  
This is based on the external model AND what your calculation does with anticipated inputs.

PolyGlot shows 1.01 mm/day

The parameters based on today's actual forecast for your function should be:
    et0 = evapotranspriation(20, 8, None, 4.4, 1120, 87, 53, 51.15, 0.23, 199)
Function result is: 7.262643528565866) (good value)

The value appearing in PolyGlot is 1.01 mm/day

Aeris Data (Raw):
{'timestamp': 1595052000, 'validTime': '2020-07-18T00:00:00-06:00', 'dateTimeISO': '2020-07-18T00:00:00-06:00', 'maxTempC': 20, 'maxTempF': 68, 'minTempC': 8, 'minTempF': 46, 'avgTempC': 14, 'avgTempF': 57, 'tempC': None, 'tempF': None, 'maxFeelslikeC': 20, 'maxFeelslikeF': 68, 'minFeelslikeC': 8, 'minFeelslikeF': 46, 'avgFeelslikeC': 14, 'avgFeelslikeF': 57, 'feelslikeC': 9, 'feelslikeF': 48, 'maxDewpointC': 13, 'maxDewpointF': 55, 'minDewpointC': 5, 'minDewpointF': 41, 'avgDewpointC': 8, 'avgDewpointF': 47, 'dewpointC': 6, 'dewpointF': 44, 'maxHumidity': 87, 'minHumidity': 53, 'humidity': 85, 'pop': 0, 'precipMM': 0, 'precipIN': 0, 'iceaccum': None, 'iceaccumMM': None, 'iceaccumIN': None, 'snowCM': 0, 'snowIN': 0, 'pressureMB': 1015, 'pressureIN': 29.96, 'windDir': 'NW', 'windDirDEG': 324, 'windSpeedKTS': 9, 'windSpeedKPH': 16, 'windSpeedMPH': 10, 'windGustKTS': 9, 'windGustKPH': 16, 'windGustMPH': 10, 'windDirMax': 'NW', 'windDirMaxDEG': 324, 'windSpeedMaxKTS': 9, 'windSpeedMaxKPH': 16, 'windSpeedMaxMPH': 10, 'windDirMin': 'SE', 'windDirMinDEG': 135, 'windSpeedMinKTS': 3, 'windSpeedMinKPH': 6, 'windSpeedMinMPH': 4, 'windDir80m': 'NNW', 'windDir80mDEG': 333, 'windSpeed80mKTS': 15, 'windSpeed80mKPH': 28, 'windSpeed80mMPH': 17, 'windGust80mKTS': 15, 'windGust80mKPH': 28, 'windGust80mMPH': 17, 'windDirMax80m': 'NNW', 'windDirMax80mDEG': 333, 'windSpeedMax80mKTS': 15, 'windSpeedMax80mKPH': 28, 'windSpeedMax80mMPH': 17, 'windDirMin80m': 'SSW', 'windDirMin80mDEG': 211, 'windSpeedMin80mKTS': 4, 'windSpeedMin80mKPH': 8, 'windSpeedMin80mMPH': 5, 'sky': 29, 'cloudsCoded': 'FW', 'weather': 'Mostly Sunny', 'weatherCoded': [], 'weatherPrimary': 'Mostly Sunny', 'weatherPrimaryCoded': '::FW', 'icon': 'pcloudy.png', 'visibilityKM': 23.9, 'visibilityMI': 14.85, 'uvi': 7, 'solradWM2': 7441, 'solradMinWM2': 0, 'solradMaxWM2': 824, 'isDay': True, 'sunrise': 1595072597, 'sunset': 1595130120, 'sunriseISO': '2020-07-18T05:43:17-06:00', 'sunsetISO': '2020-07-18T21:42:00-06:00'}


I'm not looking to be exact here, just in the ball park.  This is a significant difference...

Note:  Wind Speed is stored in km/hr as per prior changes.  Need to change to m/s for ETo, but this change would make the difference between PolyGlot and expected results even larger.    

It is possible that the issue you thought you had with Snow being one decimal place off is happening here in ETo,  **Multiplying the displayed amount by 10 (and fixing the km/h vs m/s wind speed)** brings it in the ball park.

I'll also try comparing to RainMachine and Weewx

**Comment by CompKingCanada** [comment]
You'll note that the Latitude I used was 51.15 (actual) to compare with local models.  I can't trace how this function sources the stations latitude.  I don't see it in AERIS reply data.  How is this derived?

The location I am using for API is "PWS_EW5393"

**Comment by CompKingCanada** [comment]
Looking at your code, I don't see any logic error in requiring the result to multiply by 10, and it appears you convert from km/h to m/s for wind speed.  These don't appear to be the issue.

Would be nice to figure out a way to trace the call to et3.evapotranspriation in aeris_daily.py  to see what parameters are actually being passed. and how they differ from the above expected values.

**Comment by CompKingCanada** [comment]
I think I found one issue.  

The function et3.kph2ms is not defined and is called from aeris_daily.py.  It's intent is to convert kph value to m/s value (divide by 3.6).  Is this a library function??

I don't think this is significant enough to explain my significant result variance

**Comment by CompKingCanada** [comment]
Ran some logging against this data: [Note: Paramater units = "metric"]

[Temperatures in C are wrong - appears to be have been manipulated from F to C when that wasn't necessary] [MAJOR]
  i.e. Max - 20c is not -6.66667 [which is what 20f is in Celsius]
Latitude = 0 - Wrong - Should have come from AERIS in the call for current observations [MINOR]
Ws 
WindSpeed - 

2020-07-18 13:15:22,891 Controller polyinterface      INFO     aeris_daily:update_forecast: ETo = 1.034181 0.040716
2020-07-18 13:15:22,892 Controller polyinterface      INFO     aeris_daily:update_forecast: Tmax = -6.666667
2020-07-18 13:15:22,892 Controller polyinterface      INFO     aeris_daily:update_forecast: Tmin = -13.333333
2020-07-18 13:15:22,892 Controller polyinterface      INFO     aeris_daily:update_forecast: Ws = 7.632000
2020-07-18 13:15:22,892 Controller polyinterface      INFO     aeris_daily:update_forecast: float(elevation) = 1120.000000
2020-07-18 13:15:22,893 Controller polyinterface      INFO     aeris_daily:update_forecast: max hum 87.000000
2020-07-18 13:15:22,893 Controller polyinterface      INFO     aeris_daily:update_forecast: min hum 51.000000
2020-07-18 13:15:22,893 Controller polyinterface      INFO     aeris_daily:update_forecast: latitude 0.000000
2020-07-18 13:15:22,893 Controller polyinterface      INFO     aeris_daily:update_forecast: plant 0.230000
2020-07-18 13:15:22,894 Controller polyinterface      INFO     aeris_daily:update_forecast: Day 200.000000

Code changes pending

**Comment by CompKingCanada** [comment]
Added pull requests #11 #10 

Don't know how to fix "latitude = 0" [is this a timing issue, or is it in fact a bug]

**Comment by bpaauwe** [comment]
Did you try the latest version and is it now working?

**Comment by CompKingCanada** [comment]
I saw your commits.  I am NOT seeing the "Update" option in PolyGlot (for some reason).  It worked on your prior update...

**Comment by CompKingCanada** [comment]
Wonder if the trigger for "Update" option is actually not the version # but the "Date" of the version in server.json.  Unless there is a lag before it shows up available in PolyGlot

**Comment by CompKingCanada** [comment]
"Update" option appeared after complete reboot of PI (restart of PolyGlot wasn't quite enough).  Not seeing desired results yet.  Might have to reboot ISY too.

**Comment by CompKingCanada** [comment]
Probably didn't see the updates at my poll was at 600 and I'm impatient.

Results look good now..

Thanks again!

**Comment by bpaauwe** [comment]
Just for future reference, the Polyglot store only updates once an hour, currently it's doing it at 42 minutes after the hour.  I tend to forget about that delay as I'm rarely having to update my own node servers from the store since my local version is always up-to-date.
It was just coincidence that it showed up after the reboot of the Rpi.

**Comment by CompKingCanada** [comment]
Thanks for telling me.  Now I know.  :)  A never ending learning process.

I have an issue with 'Lat' now affecting current observations, which is no longer working.  I've added comments to the commit

**Comment by bpaauwe** [comment]
Just pushed an update, It'll be about 45 more minutes before it's available on the store.

If you're comfortable with the command line, you can go to the local clone of the repository on the RPi and manually update it with 'git pull origin master'.  On the RPi, the local clones are in ~/.polyglot/nodeservers from the account that installed polyglot if I recall correctly.

**Comment by CompKingCanada** [comment]
Installed.  Fixed the issue!  Thanks

If there are any other node servers you need additional metric testing on, please let me know..
